FROM gitlab/gitlab-runner

RUN apt update && \
    wget -q https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt update && \
    apt -y install apt-transport-https && \
    apt update && \
    apt -y install dotnet-sdk-6.0 && \
    apt -y intall bc
