dweb:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      # external_url 'https://gitlab.example.com'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '5123:80'
    - '443:443'
    - '22:22'
  volumes:
    - 'D:\docker\compose\gitlab\gitlab-files:/etc/gitlab'  # have to be this way in order to work
    - 'gitlab-logs:/var/log/gitlab'
    - 'gitlab-data:/var/opt/gitlab'