version: '3'
services: 
  gitlab-runner-nine:
      image: gitlab/gitlab-runner:latest
      restart: always
      hostname: 'runner-nine'
      volumes:
        - 'C:\Temp\gitlab\gitlab-runner-nine:/etc/gitlab-runner'   # update this
        - 'gitlab-runner-nine:/var/run/docker.sock'
        - 'S:\Gitlab-runners-working-dir\docker-runner-nine:/home/gitlab/build_dir/'  # update this, to use ram drive on Windows to avoid ssd access all the time
      network_mode: "bridge"    # do not create a new network

volumes:
  gitlab-runner-nine:
  