version: '3'
services: 
    gitlab-web:
        image: 'gitlab/gitlab-ce:latest'
        restart: always
        hostname: 'gitlabweb'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                gitlab_rails['lfs_enabled'] = true
        ports:
            - '5123:5123'   # see readme, will use another port than the default port 80. Have to alter EXTERNAL_URL in gitlab.rb afterwards
            - '443:443'
            - '22:22'
        volumes:
            - D:\gitlab_ci\gitlab-web:/etc/gitlab'  # on windows, UPDATE THIS ONE ACCORDING TO FILE SYSTEM   have to be this way in order to work
            - 'gitlab-logs:/var/log/gitlab'
            - 'gitlab-data:/var/opt/gitlab'
        
        network_mode: "bridge"    # do not create a new network

volumes: 
    gitlab-logs:
    gitlab-data: